package frm;

import javax.swing.table.DefaultTableModel;
import com.itextpdf.text.*;
import com.itextpdf.text.pdf.*;
import com.itextpdf.text.pdf.draw.VerticalPositionMark;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import static java.lang.Math.E;
import java.math.BigDecimal;
import java.util.Enumeration;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.stream.Stream;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.TableColumn;
import modelo.Cuenta;
import modelo.TipoCuenta;

public class EstadoDeCapital extends javax.swing.JInternalFrame {
    java.util.List<Cuenta> lista;

    public EstadoDeCapital(java.util.List<Cuenta> lista) {
        initComponents();
        this.lista = lista;
        initTextFields();
    }
    /**
     * Creates new form EstadoDeCapital
     */
    public EstadoDeCapital() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tfCapital = new javax.swing.JTextField();
        tfUtilidad = new javax.swing.JTextField();
        tfTotalInv = new javax.swing.JTextField();
        tfGastosDN = new javax.swing.JTextField();
        tfGastosI = new javax.swing.JTextField();
        tfGastosRobo = new javax.swing.JTextField();
        tfTotalDes = new javax.swing.JTextField();
        tfCapitalContable = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("ESTADO DE CAPITAL");

        jLabel2.setText("Inversiones");

        jLabel3.setText("Capital");

        jLabel4.setText("Utilidad");

        jLabel5.setText("Desinversiones");

        jLabel6.setText("Gastos por Desastres Naturales");

        jLabel7.setText("Gastos por Incendio");

        jLabel8.setText("Gastos por Robo");

        jLabel9.setText("Total de Inversiones");

        jLabel10.setText("Total de desinversiones");

        jLabel11.setText("Capital Contable");

        tfCapital.setEditable(false);

        tfUtilidad.setEditable(false);

        tfTotalInv.setEditable(false);

        tfGastosDN.setEditable(false);

        tfGastosI.setEditable(false);

        tfGastosRobo.setEditable(false);

        tfTotalDes.setEditable(false);
        tfTotalDes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTotalDesActionPerformed(evt);
            }
        });

        tfCapitalContable.setEditable(false);

        jButton1.setText("Guardar como PDF");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(5, 5, 5)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel3))
                                        .addGap(144, 144, 144)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tfCapital, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tfUtilidad, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel8))
                                        .addGap(5, 5, 5)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tfGastosRobo, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tfGastosI, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tfGastosDN, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(150, 150, 150)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel2))))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfTotalDes, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfCapitalContable, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfTotalInv, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(tfCapital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfUtilidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tfTotalInv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfGastosDN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfGastosI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(tfGastosRobo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(tfTotalDes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfCapitalContable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfTotalDesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTotalDesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTotalDesActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            Document document = new Document();
            JFileChooser open = new JFileChooser();
            PdfPTable table = new PdfPTable(3);
            
            open.setFileFilter(new FileNameExtensionFilter("archivo pdf", "pdf"));
            open.showSaveDialog(this);

            PdfWriter.getInstance(document, new FileOutputStream(open.getSelectedFile() + ".pdf"));
            document.open();
            Paragraph p = new Paragraph("PROPLASTIC S.A. DE C.V.");
            p.setAlignment(Element.ALIGN_CENTER);
            document.add(p);
            p = new Paragraph("ESTADO DE CAPITAL");
            p.setAlignment(Element.ALIGN_CENTER);
            document.add(p);
            p = new Paragraph("DEL ____ AL ____ DE 20___");
            p.setAlignment(Element.ALIGN_CENTER);
            document.add(p);
            document.add(Chunk.NEWLINE);

            addRows(table);
            //Codigo de la tabla 

            document.add(table);
            document.close();

        } catch (DocumentException ex) {
            Logger.getLogger(EstadoDeCapital.class.getName()).log(Level.SEVERE, null, ex);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(EstadoDeCapital.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EstadoDeCapital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EstadoDeCapital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EstadoDeCapital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EstadoDeCapital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EstadoDeCapital().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField tfCapital;
    private javax.swing.JTextField tfCapitalContable;
    private javax.swing.JTextField tfGastosDN;
    private javax.swing.JTextField tfGastosI;
    private javax.swing.JTextField tfGastosRobo;
    private javax.swing.JTextField tfTotalDes;
    private javax.swing.JTextField tfTotalInv;
    private javax.swing.JTextField tfUtilidad;
    // End of variables declaration//GEN-END:variables

    private void addRows(PdfPTable table) {
        Font fontBold = FontFactory.getFont(FontFactory.HELVETICA, 12, Font.BOLD);
        Font fontItalic = FontFactory.getFont(FontFactory.HELVETICA, 12, Font.ITALIC);
        PdfPCell cell;
        cell = new PdfPCell(new Phrase("Inversiones",fontBold));
        cell.setColspan(3);
        table.addCell(cell);

        cell = new PdfPCell(new Phrase("Capital"));
        table.addCell(cell);
        cell = new PdfPCell(new Phrase(tfCapital.getText()));
        cell.setColspan(2);
        table.addCell(cell);

        cell = new PdfPCell(new Phrase("Utilidad"));
        table.addCell(cell);
        cell = new PdfPCell(new Phrase(tfUtilidad.getText()));
        cell.setColspan(2);
        table.addCell(cell);

        cell = new PdfPCell(new Phrase("Total de Inversiones",fontItalic));
        cell.setColspan(2);
        table.addCell(cell);
        cell = new PdfPCell(new Phrase(tfTotalInv.getText()));
        table.addCell(cell);

        cell = new PdfPCell(new Phrase("Desinversiones",fontBold));
        cell.setColspan(3);
        table.addCell(cell);

        cell = new PdfPCell(new Phrase("Gastos por Desastres Naturales"));
        table.addCell(cell);
        cell = new PdfPCell(new Phrase(tfGastosDN.getText()));
        cell.setColspan(2);
        table.addCell(cell);

        cell = new PdfPCell(new Phrase("Gastos por Incendio"));
        table.addCell(cell);
        cell = new PdfPCell(new Phrase(tfGastosI.getText()));
        cell.setColspan(2);
        table.addCell(cell);

        cell = new PdfPCell(new Phrase("Gastos por Robo"));
        table.addCell(cell);
        cell = new PdfPCell(new Phrase(tfGastosRobo.getText()));
        cell.setColspan(2);
        table.addCell(cell);

        cell = new PdfPCell(new Phrase("Total de Desinversiones",fontItalic));
        cell.setColspan(2);
        table.addCell(cell);
        cell = new PdfPCell(new Phrase(tfTotalDes.getText()));
        table.addCell(cell);

        cell = new PdfPCell(new Phrase("Capital Contable",fontItalic));
        cell.setColspan(2);
        table.addCell(cell);
        cell = new PdfPCell(new Phrase(tfCapitalContable.getText()));
        table.addCell(cell);
    }

    private void initTextFields() {
        for(Cuenta c: lista){
            BigDecimal saldo = new BigDecimal(0.0);
            if(c.getSumaDebe().compareTo(new BigDecimal(0.0))!=0)
                saldo = c.getSumaDebe();
            else
                saldo = c.getSumaHaber();
            switch(c.getCodigo()){
                case 31:{
                    tfCapital.setText(String.valueOf(saldo));
                    break;
                }
                case 321:{
                    tfUtilidad.setText(String.valueOf(saldo));
                    break;
                }
                case 4161:{
                    tfGastosDN.setText(String.valueOf(saldo));
                    break;
                }
                case 4162:{
                    tfGastosI.setText(String.valueOf(saldo));
                    break;
                }
                case 4163:{
                    tfGastosRobo.setText(String.valueOf(saldo));
                    break;
                }
            }
        }
        Double capital = Double.parseDouble(tfCapital.getText());
        Double utilidad = Double.parseDouble(tfUtilidad.getText());
        Double gastosDN = Double.parseDouble(tfGastosDN.getText());
        Double gastosI = Double.parseDouble(tfGastosI.getText());
        Double gastosRobo = Double.parseDouble(tfGastosRobo.getText());
        Double inversion = capital+utilidad;
        Double desinversion = gastosDN+gastosI+gastosRobo;
        tfTotalInv.setText(String.valueOf(inversion));
        tfTotalDes.setText(String.valueOf(desinversion));
        tfCapitalContable.setText(String.valueOf(inversion-desinversion));
        
    }
}
