/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frm;

import Clases.MateriaPrimaTableModel;
import db.Consulta;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.swing.table.DefaultTableColumnModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import modelo.EstadoPeriodo;
import modelo.Kardex;
import modelo.LineaKardex;
import modelo.PeriodoContable;
import modelo.TipoKardex;

/**
 *
 * @author Sony
 */
public class MateriaPrimaKardex extends javax.swing.JInternalFrame {

    private MateriaPrimaTableModel materiaPrimaTModel = new MateriaPrimaTableModel();
    /**
     * Creates new form MateriaPrimaKardex
     */
    public MateriaPrimaKardex() {
        initComponents();

        inicializarColumnas();
        recuperarDatosPeriodoActual();
    }

    private void inicializarColumnas() {
        TableColumnModel tColumn = new DefaultTableColumnModel();

        for (int i = 0; i < 10; i++) {
            TableColumn col = new TableColumn(i);

            switch (i) {
                case 0:
                    col.setHeaderValue("Fecha");
                    break;
                case 1:
                    col.setHeaderValue("Cantidad");
                    break;
                case 2:
                    col.setHeaderValue("Costo Unitario");
                    break;
                case 3:
                    col.setHeaderValue("Monto");
                    break;
                case 4:
                    col.setHeaderValue("Cantidad");
                    break;
                case 5:
                    col.setHeaderValue("Costo Unitario");
                    break;
                case 6:
                    col.setHeaderValue("Monto");
                    break;
                case 7:
                    col.setHeaderValue("Cantidad");
                    break;
                case 8:
                    col.setHeaderValue("Costo Unitario");
                    break;
                case 9:
                    col.setHeaderValue("Monto");

            }
            tColumn.addColumn(col);
        }
        tablaMateriaP.setColumnModel(tColumn);

    }
    
    private void recuperarDatosPeriodoActual(){
        materiaPrimaTModel.getLineasKardex().clear();
        Consulta c = new Consulta();
        c.inicializar();
        
        PeriodoContable periodoActual = (PeriodoContable)c.obtenerYFiltrar("PeriodoContable", "estadoPeriodo="+EstadoPeriodo.ESTADO_EN_CURSO).get(0);
        
        Kardex kardex = (Kardex)c.obtenerYFiltrar("Kardex", "tipoKardex="+TipoKardex.KARDEX_MATERIA_PRIMA+" AND "+"periodoContable="+periodoActual.getIdPeriodo()).get(0);

        ArrayList<LineaKardex> lineas = (ArrayList<LineaKardex>)c.obtenerYFiltrar("LineaKardex", "kardex="+kardex.getIdKardex()+" ORDER BY idLineaKardex");
        
        materiaPrimaTModel.setLineasKardex(lineas);

        c.cerrarConexion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lMateriaP = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaMateriaP = new javax.swing.JTable();
        lEntrada1 = new javax.swing.JLabel();
        lSalida1 = new javax.swing.JLabel();
        lSaldo1 = new javax.swing.JLabel();

        setClosable(true);

        lMateriaP.setText("Costo de Materia Prima");

        tablaMateriaP.setModel(materiaPrimaTModel);
        jScrollPane1.setViewportView(tablaMateriaP);

        lEntrada1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lEntrada1.setText("Entradas");

        lSalida1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lSalida1.setText("Salidas");

        lSaldo1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lSaldo1.setText("Saldos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(lEntrada1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lSalida1)
                .addGap(269, 269, 269)
                .addComponent(lSaldo1)
                .addGap(197, 197, 197))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(lMateriaP))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1075, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lMateriaP)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lEntrada1)
                    .addComponent(lSalida1)
                    .addComponent(lSaldo1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(133, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lEntrada1;
    private javax.swing.JLabel lMateriaP;
    private javax.swing.JLabel lSaldo1;
    private javax.swing.JLabel lSalida1;
    private javax.swing.JTable tablaMateriaP;
    // End of variables declaration//GEN-END:variables
}
