/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frm;

import Clases.MateriaPrimaTableModel;
import db.Consulta;
import java.awt.Dimension;
import java.awt.Frame;
import java.awt.Point;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.swing.JInternalFrame;
import javax.swing.table.DefaultTableColumnModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import modelo.EstadoPeriodo;
import modelo.Kardex;
import modelo.LineaKardex;
import modelo.PeriodoContable;
import modelo.TipoKardex;

/**
 *
 * @author Sony
 */
public class MateriaPrimaKardex extends javax.swing.JInternalFrame {

    private MateriaPrimaTableModel materiaPrimaTModel = new MateriaPrimaTableModel();
    
    private Kardex kardexDeMateriaPrima;
    /**
     * Creates new form MateriaPrimaKardex
     */
    public MateriaPrimaKardex() {
        initComponents();

        inicializarColumnas();
        recuperarDatosPeriodoActual();
    }

    private void inicializarColumnas() {
        TableColumnModel tColumn = new DefaultTableColumnModel();

        for (int i = 0; i < 10; i++) {
            TableColumn col = new TableColumn(i);

            switch (i) {
                case 0:
                    col.setHeaderValue("Fecha");
                    break;
                case 1:
                    col.setHeaderValue("Cantidad");
                    break;
                case 2:
                    col.setHeaderValue("Costo Unitario");
                    break;
                case 3:
                    col.setHeaderValue("Monto");
                    break;
                case 4:
                    col.setHeaderValue("Cantidad");
                    break;
                case 5:
                    col.setHeaderValue("Costo Unitario");
                    break;
                case 6:
                    col.setHeaderValue("Monto");
                    break;
                case 7:
                    col.setHeaderValue("Cantidad");
                    break;
                case 8:
                    col.setHeaderValue("Costo Unitario");
                    break;
                case 9:
                    col.setHeaderValue("Monto");

            }
            tColumn.addColumn(col);
        }
        tablaMateriaP.setColumnModel(tColumn);

    }
    
    public void recuperarDatosPeriodoActual(){
        materiaPrimaTModel.getLineasKardex().clear();
        Consulta c = new Consulta();
        c.inicializar();
        
        PeriodoContable periodoActual = (PeriodoContable)c.obtenerYFiltrar("PeriodoContable", "estadoPeriodo="+EstadoPeriodo.ESTADO_EN_CURSO).get(0);
        
        ArrayList<Kardex> kardex = (ArrayList<Kardex>)c.obtenerYFiltrar("Kardex", "tipoKardex="+TipoKardex.KARDEX_MATERIA_PRIMA+" AND "+"periodoContable="+periodoActual.getIdPeriodo());
        
        if(kardex.size()>0){
            kardexDeMateriaPrima = kardex.get(0);
            ArrayList<LineaKardex> lineas = (ArrayList<LineaKardex>)c.obtenerYFiltrar("LineaKardex", "kardex="+kardex.get(0).getIdKardex()+" ORDER BY idLineaKardex");
            materiaPrimaTModel.setLineasKardex(lineas);
        }
            
        c.cerrarConexion();
        
        materiaPrimaTModel.fireTableDataChanged();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lMateriaP = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaMateriaP = new javax.swing.JTable();
        lEntrada1 = new javax.swing.JLabel();
        lSalida1 = new javax.swing.JLabel();
        lSaldo1 = new javax.swing.JLabel();
        btnEntrada = new javax.swing.JButton();
        btnSalida = new javax.swing.JButton();

        setClosable(true);
        setTitle("Kardex Materia Prima");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        lMateriaP.setText("Costo de Materia Prima");

        tablaMateriaP.setModel(materiaPrimaTModel);
        jScrollPane1.setViewportView(tablaMateriaP);

        lEntrada1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lEntrada1.setText("Entradas");

        lSalida1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lSalida1.setText("Salidas");

        lSaldo1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lSaldo1.setText("Saldos");

        btnEntrada.setText("Nueva Entrada");
        btnEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntradaActionPerformed(evt);
            }
        });

        btnSalida.setText("Nueva Salida");
        btnSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalidaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(lEntrada1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lSalida1)
                .addGap(269, 269, 269)
                .addComponent(lSaldo1)
                .addGap(197, 197, 197))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(lMateriaP))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1075, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEntrada)
                .addGap(42, 42, 42)
                .addComponent(btnSalida)
                .addGap(200, 200, 200))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lMateriaP)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lEntrada1)
                    .addComponent(lSalida1)
                    .addComponent(lSaldo1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEntrada)
                    .addComponent(btnSalida))
                .addContainerGap(96, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntradaActionPerformed
        NuevaLineaKardexMateriaPrima dialogo = new NuevaLineaKardexMateriaPrima(NuevaLineaKardexMateriaPrima.ENTRADA, kardexDeMateriaPrima);
        dialogo.setLocation(centrar(dialogo));
        getParent().add(dialogo);
        dialogo.show();
    }//GEN-LAST:event_btnEntradaActionPerformed

    private void btnSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalidaActionPerformed
        NuevaLineaKardexMateriaPrima dialogo = new NuevaLineaKardexMateriaPrima(NuevaLineaKardexMateriaPrima.SALIDA, kardexDeMateriaPrima);
        dialogo.setLocation(centrar(dialogo));
        getParent().add(dialogo);
        dialogo.show();
    }//GEN-LAST:event_btnSalidaActionPerformed

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        
        if(this.isSelected)
            recuperarDatosPeriodoActual();
    }//GEN-LAST:event_formInternalFrameActivated

    public  Point centrar(JInternalFrame frame){
        Dimension desktopSize = this.getSize();
        Dimension jInternalFrameSize = frame.getSize();
        Point punto = new Point((desktopSize.width - jInternalFrameSize.width)/2,(desktopSize.height- jInternalFrameSize.height)/2);
        
        return punto;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrada;
    private javax.swing.JButton btnSalida;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lEntrada1;
    private javax.swing.JLabel lMateriaP;
    private javax.swing.JLabel lSaldo1;
    private javax.swing.JLabel lSalida1;
    private javax.swing.JTable tablaMateriaP;
    // End of variables declaration//GEN-END:variables
}
