/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frm;

import javax.swing.table.DefaultTableColumnModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Sony
 */
public class PenPKardex extends javax.swing.JInternalFrame {

    /**
     * Creates new form PenPKardex
     */
    public PenPKardex() {
        initComponents();
        
        inicializarColumnas();
    }

    private void inicializarColumnas(){
        TableColumnModel tColumn = new DefaultTableColumnModel();
        
        for (int i=0; i<10; i++){
            TableColumn col= new TableColumn(i);
            
            switch (i){
                case 0:
                    col.setHeaderValue("Fecha");
                    break;
                case 1:
                    col.setHeaderValue("Cantidad");
                    break;
                case 2:
                    col.setHeaderValue("Costo Unitario");
                    break;
                case 3:
                    col.setHeaderValue("Monto");
                    break;
                case 4:
                    col.setHeaderValue("Cantidad");
                    break;
                case 5:
                    col.setHeaderValue("Costo Unitario");
                    break;
                case 6:
                    col.setHeaderValue("Monto");
                    break;
                case 7:
                    col.setHeaderValue("Cantidad");
                    break;
                case 8:
                    col.setHeaderValue("Costo Unitario");
                    break;
                case 9:
                    col.setHeaderValue("Monto");
                
            }
            tColumn.addColumn(col);
        }
        tablaPenP.setColumnModel(tColumn);
        
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lPenP = new javax.swing.JLabel();
        lEntrada2 = new javax.swing.JLabel();
        lSalida2 = new javax.swing.JLabel();
        lSaldo2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPenP = new javax.swing.JTable();

        lPenP.setText("Costos de Producto en Proceso");

        lEntrada2.setText("Entradas");

        lSalida2.setText("Salidas");

        lSaldo2.setText("Saldos");

        tablaPenP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaPenP);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lPenP))
                .addContainerGap(43, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(lEntrada2)
                .addGap(126, 126, 126)
                .addComponent(lSalida2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lSaldo2)
                .addGap(117, 117, 117))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lPenP)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lEntrada2)
                    .addComponent(lSalida2)
                    .addComponent(lSaldo2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lEntrada2;
    private javax.swing.JLabel lPenP;
    private javax.swing.JLabel lSaldo2;
    private javax.swing.JLabel lSalida2;
    private javax.swing.JTable tablaPenP;
    // End of variables declaration//GEN-END:variables
}
