package modelo;
// Generated 10-15-2017 11:15:46 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Cuenta generated by hbm2java
 */
public class Cuenta  implements java.io.Serializable {


     private int idCuenta;
     private Cuenta cuenta;
     private TipoCuenta tipoCuenta;
     private int codigo;
     private String nombreCuenta;
     private BigDecimal sumaDebe;
     private BigDecimal sumaHaber;
     private BigDecimal saldo;
     private Boolean ajustable;
     private Boolean operable;
     private Set cuentas = new HashSet(0);
     private Set lineaDePartidas = new HashSet(0);

    public Cuenta() {
    }

	
    public Cuenta(int idCuenta, TipoCuenta tipoCuenta, int codigo, String nombreCuenta) {
        this.idCuenta = idCuenta;
        this.tipoCuenta = tipoCuenta;
        this.codigo = codigo;
        this.nombreCuenta = nombreCuenta;
    }
    public Cuenta(int idCuenta, Cuenta cuenta, TipoCuenta tipoCuenta, int codigo, String nombreCuenta, BigDecimal sumaDebe, BigDecimal sumaHaber, BigDecimal saldo, Boolean ajustable, Boolean operable, Set cuentas, Set lineaDePartidas) {
       this.idCuenta = idCuenta;
       this.cuenta = cuenta;
       this.tipoCuenta = tipoCuenta;
       this.codigo = codigo;
       this.nombreCuenta = nombreCuenta;
       this.sumaDebe = sumaDebe;
       this.sumaHaber = sumaHaber;
       this.saldo = saldo;
       this.ajustable = ajustable;
       this.operable = operable;
       this.cuentas = cuentas;
       this.lineaDePartidas = lineaDePartidas;
    }
   
    public int getIdCuenta() {
        return this.idCuenta;
    }
    
    public void setIdCuenta(int idCuenta) {
        this.idCuenta = idCuenta;
    }
    public Cuenta getCuenta() {
        return this.cuenta;
    }
    
    public void setCuenta(Cuenta cuenta) {
        this.cuenta = cuenta;
    }
    public TipoCuenta getTipoCuenta() {
        return this.tipoCuenta;
    }
    
    public void setTipoCuenta(TipoCuenta tipoCuenta) {
        this.tipoCuenta = tipoCuenta;
    }
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    public String getNombreCuenta() {
        return this.nombreCuenta;
    }
    
    public void setNombreCuenta(String nombreCuenta) {
        this.nombreCuenta = nombreCuenta;
    }
    public BigDecimal getSumaDebe() {
        return this.sumaDebe;
    }
    
    public void setSumaDebe(BigDecimal sumaDebe) {
        this.sumaDebe = sumaDebe;
    }
    public BigDecimal getSumaHaber() {
        return this.sumaHaber;
    }
    
    public void setSumaHaber(BigDecimal sumaHaber) {
        this.sumaHaber = sumaHaber;
    }
    public BigDecimal getSaldo() {
        return this.saldo;
    }
    
    public void setSaldo(BigDecimal saldo) {
        this.saldo = saldo;
    }
    public Boolean getAjustable() {
        return this.ajustable;
    }
    
    public void setAjustable(Boolean ajustable) {
        this.ajustable = ajustable;
    }
    public Boolean getOperable() {
        return this.operable;
    }
    
    public void setOperable(Boolean operable) {
        this.operable = operable;
    }
    public Set getCuentas() {
        return this.cuentas;
    }
    
    public void setCuentas(Set cuentas) {
        this.cuentas = cuentas;
    }
    public Set getLineaDePartidas() {
        return this.lineaDePartidas;
    }
    
    public void setLineaDePartidas(Set lineaDePartidas) {
        this.lineaDePartidas = lineaDePartidas;
    }




}


