package modelo;
// Generated 11-03-2017 09:45:10 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Empleados generated by hbm2java
 */
public class Empleados  implements java.io.Serializable {


     private int idEmpleado;
     private String nombreEmpleado;
     private String apellidoEmpleado;
     private Set usuarios = new HashSet(0);

    public Empleados() {
    }

	
    public Empleados(int idEmpleado, String nombreEmpleado, String apellidoEmpleado) {
        this.idEmpleado = idEmpleado;
        this.nombreEmpleado = nombreEmpleado;
        this.apellidoEmpleado = apellidoEmpleado;
    }
    public Empleados(int idEmpleado, String nombreEmpleado, String apellidoEmpleado, Set usuarios) {
       this.idEmpleado = idEmpleado;
       this.nombreEmpleado = nombreEmpleado;
       this.apellidoEmpleado = apellidoEmpleado;
       this.usuarios = usuarios;
    }
   
    public int getIdEmpleado() {
        return this.idEmpleado;
    }
    
    public void setIdEmpleado(int idEmpleado) {
        this.idEmpleado = idEmpleado;
    }
    public String getNombreEmpleado() {
        return this.nombreEmpleado;
    }
    
    public void setNombreEmpleado(String nombreEmpleado) {
        this.nombreEmpleado = nombreEmpleado;
    }
    public String getApellidoEmpleado() {
        return this.apellidoEmpleado;
    }
    
    public void setApellidoEmpleado(String apellidoEmpleado) {
        this.apellidoEmpleado = apellidoEmpleado;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }




}


