package modelo;
// Generated 10-15-2017 11:15:46 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * LineaDePartida generated by hbm2java
 */
public class LineaDePartida  implements java.io.Serializable {


     private int idLinea;
     private Cuenta cuenta;
     private Partida partida;
     private BigDecimal debe;
     private BigDecimal haber;

    public LineaDePartida() {
    }

	
    public LineaDePartida(int idLinea, Cuenta cuenta, Partida partida) {
        this.idLinea = idLinea;
        this.cuenta = cuenta;
        this.partida = partida;
    }
    public LineaDePartida(int idLinea, Cuenta cuenta, Partida partida, BigDecimal debe, BigDecimal haber) {
       this.idLinea = idLinea;
       this.cuenta = cuenta;
       this.partida = partida;
       this.debe = debe;
       this.haber = haber;
    }
   
    public int getIdLinea() {
        return this.idLinea;
    }
    
    public void setIdLinea(int idLinea) {
        this.idLinea = idLinea;
    }
    public Cuenta getCuenta() {
        return this.cuenta;
    }
    
    public void setCuenta(Cuenta cuenta) {
        this.cuenta = cuenta;
    }
    public Partida getPartida() {
        return this.partida;
    }
    
    public void setPartida(Partida partida) {
        this.partida = partida;
    }
    public BigDecimal getDebe() {
        return this.debe;
    }
    
    public void setDebe(BigDecimal debe) {
        this.debe = debe;
    }
    public BigDecimal getHaber() {
        return this.haber;
    }
    
    public void setHaber(BigDecimal haber) {
        this.haber = haber;
    }




}


