package modelo;
// Generated 10-15-2017 11:15:46 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Partida generated by hbm2java
 */
public class Partida  implements java.io.Serializable {


     private int idPartida;
     private PeriodoContable periodoContable;
     private Usuario usuario;
     private Date fecha;
     private String descripcion;
     private Set lineaDePartidas = new HashSet(0);

    public Partida() {
    }

	
    public Partida(int idPartida, PeriodoContable periodoContable, Usuario usuario, Date fecha, String descripcion) {
        this.idPartida = idPartida;
        this.periodoContable = periodoContable;
        this.usuario = usuario;
        this.fecha = fecha;
        this.descripcion = descripcion;
    }
    public Partida(int idPartida, PeriodoContable periodoContable, Usuario usuario, Date fecha, String descripcion, Set lineaDePartidas) {
       this.idPartida = idPartida;
       this.periodoContable = periodoContable;
       this.usuario = usuario;
       this.fecha = fecha;
       this.descripcion = descripcion;
       this.lineaDePartidas = lineaDePartidas;
    }
   
    public int getIdPartida() {
        return this.idPartida;
    }
    
    public void setIdPartida(int idPartida) {
        this.idPartida = idPartida;
    }
    public PeriodoContable getPeriodoContable() {
        return this.periodoContable;
    }
    
    public void setPeriodoContable(PeriodoContable periodoContable) {
        this.periodoContable = periodoContable;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getLineaDePartidas() {
        return this.lineaDePartidas;
    }
    
    public void setLineaDePartidas(Set lineaDePartidas) {
        this.lineaDePartidas = lineaDePartidas;
    }




}


