package modelo;
// Generated 11-03-2017 09:45:10 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Sesiones generated by hbm2java
 */
public class Sesiones  implements java.io.Serializable {


     private int idSesion;
     private String keySesion;
     private Boolean activa;
     private Date inicio;
     private Date fin;
     private Set usuarios = new HashSet(0);

    public Sesiones() {
    }

	
    public Sesiones(int idSesion, String keySesion) {
        this.idSesion = idSesion;
        this.keySesion = keySesion;
    }
    public Sesiones(int idSesion, String keySesion, Boolean activa, Date inicio, Date fin, Set usuarios) {
       this.idSesion = idSesion;
       this.keySesion = keySesion;
       this.activa = activa;
       this.inicio = inicio;
       this.fin = fin;
       this.usuarios = usuarios;
    }
   
    public int getIdSesion() {
        return this.idSesion;
    }
    
    public void setIdSesion(int idSesion) {
        this.idSesion = idSesion;
    }
    public String getKeySesion() {
        return this.keySesion;
    }
    
    public void setKeySesion(String keySesion) {
        this.keySesion = keySesion;
    }
    public Boolean getActiva() {
        return this.activa;
    }
    
    public void setActiva(Boolean activa) {
        this.activa = activa;
    }
    public Date getInicio() {
        return this.inicio;
    }
    
    public void setInicio(Date inicio) {
        this.inicio = inicio;
    }
    public Date getFin() {
        return this.fin;
    }
    
    public void setFin(Date fin) {
        this.fin = fin;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }




}


