package modelo;
// Generated 11-04-2017 04:08:07 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Sesiones generated by hbm2java
 */
public class Sesiones  implements java.io.Serializable {


     private int idSesion;
     private Usuario usuario;
     private String keySesion;
     private Boolean activa;
     private Date inicio;
     private Date fin;

    public Sesiones() {
    }

	
    public Sesiones(int idSesion, String keySesion) {
        this.idSesion = idSesion;
        this.keySesion = keySesion;
    }
    public Sesiones(int idSesion, Usuario usuario, String keySesion, Boolean activa, Date inicio, Date fin) {
       this.idSesion = idSesion;
       this.usuario = usuario;
       this.keySesion = keySesion;
       this.activa = activa;
       this.inicio = inicio;
       this.fin = fin;
    }
   
    public int getIdSesion() {
        return this.idSesion;
    }
    
    public void setIdSesion(int idSesion) {
        this.idSesion = idSesion;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getKeySesion() {
        return this.keySesion;
    }
    
    public void setKeySesion(String keySesion) {
        this.keySesion = keySesion;
    }
    public Boolean getActiva() {
        return this.activa;
    }
    
    public void setActiva(Boolean activa) {
        this.activa = activa;
    }
    public Date getInicio() {
        return this.inicio;
    }
    
    public void setInicio(Date inicio) {
        this.inicio = inicio;
    }
    public Date getFin() {
        return this.fin;
    }
    
    public void setFin(Date fin) {
        this.fin = fin;
    }

    public class UserValidator {

        public UserValidator() {
        }
    }




}


