package modelo;
// Generated 11-03-2017 09:45:10 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Sesiones generated by hbm2java
 */
public class Sesiones  implements java.io.Serializable {


     private int idSesion;
     private String keySesion;
     private Set usuarios = new HashSet(0);

    public Sesiones() {
    }

	
    public Sesiones(int idSesion, String keySesion) {
        this.idSesion = idSesion;
        this.keySesion = keySesion;
    }
    public Sesiones(int idSesion, String keySesion, Set usuarios) {
       this.idSesion = idSesion;
       this.keySesion = keySesion;
       this.usuarios = usuarios;
    }
   
    public int getIdSesion() {
        return this.idSesion;
    }
    
    public void setIdSesion(int idSesion) {
        this.idSesion = idSesion;
    }
    public String getKeySesion() {
        return this.keySesion;
    }
    
    public void setKeySesion(String keySesion) {
        this.keySesion = keySesion;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }




}


