package modelo;
// Generated 10-15-2017 11:15:46 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TipoCuenta generated by hbm2java
 */
public class TipoCuenta  implements java.io.Serializable {


     private int idTipo;
     private String nombreTipo;
     private Set cuentas = new HashSet(0);

    public TipoCuenta() {
    }

	
    public TipoCuenta(int idTipo, String nombreTipo) {
        this.idTipo = idTipo;
        this.nombreTipo = nombreTipo;
    }
    public TipoCuenta(int idTipo, String nombreTipo, Set cuentas) {
       this.idTipo = idTipo;
       this.nombreTipo = nombreTipo;
       this.cuentas = cuentas;
    }
   
    public int getIdTipo() {
        return this.idTipo;
    }
    
    public void setIdTipo(int idTipo) {
        this.idTipo = idTipo;
    }
    public String getNombreTipo() {
        return this.nombreTipo;
    }
    
    public void setNombreTipo(String nombreTipo) {
        this.nombreTipo = nombreTipo;
    }
    public Set getCuentas() {
        return this.cuentas;
    }
    
    public void setCuentas(Set cuentas) {
        this.cuentas = cuentas;
    }




}


