package modelo;
// Generated 11-03-2017 09:45:10 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private int idUsuario;
     private Empleados empleados;
     private Roles roles;
     private Sesiones sesiones;
     private String username;
     private String password;
     private Boolean active;
     private Set partidas = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(int idUsuario, String username, String password) {
        this.idUsuario = idUsuario;
        this.username = username;
        this.password = password;
    }
    public Usuario(int idUsuario, Empleados empleados, Roles roles, Sesiones sesiones, String username, String password, Boolean active, Set partidas) {
       this.idUsuario = idUsuario;
       this.empleados = empleados;
       this.roles = roles;
       this.sesiones = sesiones;
       this.username = username;
       this.password = password;
       this.active = active;
       this.partidas = partidas;
    }
   
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Empleados getEmpleados() {
        return this.empleados;
    }
    
    public void setEmpleados(Empleados empleados) {
        this.empleados = empleados;
    }
    public Roles getRoles() {
        return this.roles;
    }
    
    public void setRoles(Roles roles) {
        this.roles = roles;
    }
    public Sesiones getSesiones() {
        return this.sesiones;
    }
    
    public void setSesiones(Sesiones sesiones) {
        this.sesiones = sesiones;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Boolean getActive() {
        return this.active;
    }
    
    public void setActive(Boolean active) {
        this.active = active;
    }
    public Set getPartidas() {
        return this.partidas;
    }
    
    public void setPartidas(Set partidas) {
        this.partidas = partidas;
    }




}


