package modelo;
// Generated 10-15-2017 11:15:46 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private int idUsuario;
     private String username;
     private String password;
     private String nombreUsuario;
     private Set partidas = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(int idUsuario, String username, String password, String nombreUsuario) {
        this.idUsuario = idUsuario;
        this.username = username;
        this.password = password;
        this.nombreUsuario = nombreUsuario;
    }
    public Usuario(int idUsuario, String username, String password, String nombreUsuario, Set partidas) {
       this.idUsuario = idUsuario;
       this.username = username;
       this.password = password;
       this.nombreUsuario = nombreUsuario;
       this.partidas = partidas;
    }
   
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getNombreUsuario() {
        return this.nombreUsuario;
    }
    
    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
    }
    public Set getPartidas() {
        return this.partidas;
    }
    
    public void setPartidas(Set partidas) {
        this.partidas = partidas;
    }




}


